### PR TITLE
Extend to use wl-clipboard in wayland

### PR DESCRIPTION
**Pull request by cinghiopinghio**
In wayland there is no `xclip`.
This small commit extend your useful plugin to use `wl-clipboard` in wayland.
I have no X11 in my laptop, so it should be tested before merging.

### CODE REVIEW

**Comment by ferrine** [comment]
I have x11 and will check that

**Comment by lucasdf** [comment]
I tested it using x11 and it worked fine here,

**Comment by ferrine** [comment]
@lucasdf Thanks for the reminder, I also successfully updated to the pr branch and tried it out.

**Comment by ferrine** [comment]
Thanks, @cinghiopinghio !

**Comment by cinghiopinghio** [comment]
you welcome, Happy it was useful.

**Pull request merged**
